### ISSUE TITLE
combineLatest

### ISSUE THREAD

**Issue by ccorcos** [paldepind/flyd#10]
http://reactivex.io/documentation/operators/combinelatest.html

This is also a helpful function. It can often be used with switchOnNext as well. 

```js

searchStream = flyd.stream('')

searchStream.switchMapCombineLatest(function(query) {
  searchResultsStream(query)
}).map(function(query, results) {
  // now I have the results AND the query!
})
```

Now `switchMapCombineLatest` is kind of a long name here. RxJS uses `combineLatest(stream1, stream2)` but I find it most useful inline like the example I gave you.

**Comment by paldepind** [comment]
Maybe I'm missing something, but isn't this similar to [`flyd-lift`](https://github.com/paldepind/flyd-lift) or what Elm calls [map2](http://package.elm-lang.org/packages/elm-lang/core/1.1.1/Signal#map2)?

`lift` allows you to map a function taking `n` arguments over `n` streams. The result stream is updated whenever any of the `n` streams change.

**Comment by ccorcos** [comment]
Very similar to lift. I suppose you could accomplish it like this:

```js
var args2Array = function(a, b) {
  return [a,b]
};

var n1 = stream(1),
    n2 = stream(4);

var latest = lift(args2Array, n1, n2);

latest(); // [1,4]
```

The difference here is a switch functionality where n2 is created inside of n1.

```js
var n1 = stream(1);

n1.map(function(x) {
  return anotherStream(x)
}).map(function(z) {
  // z = [x,y] where
  // x is from n1, and y is from anotherStream
});
```

Suppose `anotherStream(x)` returns a stream using `x`. Thus we want to end `anotherStream` when `n1` changes or ends. We could use `takeUntil` for the switch functionality, but then we need some kind of combine latest:

```js
var n1 = stream(1);

n1.switchMap(function(x) {
  var n2 = flyd.takeUntil(n1, anotherStream(x))
  return flyd.lift(args2Array, n1, n2)
})
```

Well there we go. I guess thats the functionally what I'm looking for. 


Now the question is how to refactor this... I can think of a few ways:

Maybe `combine` should be a function a lot like lift except the following difference:

```js
a = flyd.lift(args2Array, n1, n2)
b = flyd.combine(n1, n2)
```

`a` and `b` are pretty much the same, except when `b` ends, then `n2` ends as well. then we have this:

```js
var n1 = stream(1);

n1.switchMap(function(x) {
  return flyd.combine(n1, anotherStream(x))
})
```

`combine` is probably not the best word though. 

Another way could be something like this:

```js
combine = function(f, s) {
  return switchMap(function(x) {
    return flyd.lift(args2array, s, f(x).takeUntil(s))
}
```

Too many names right now... The point though, is that you can map over a stream, creating a new stream that emits in parallel, much like the first example given in this thread...

**Comment by paldepind** [comment]
I'm not completely following you. Consider this example of `combineLatest` from the Rx documentation:

```javascript
/* Have staggering intervals */
var source1 = Rx.Observable.interval(100)
    .map(function (i) { return 'First: ' + i; });

var source2 = Rx.Observable.interval(150)
    .map(function (i) { return 'Second: ' + i; });

// Combine latest of source1 and source2 whenever either gives a value
var source = source1.combineLatest(
        source2,
        function (s1, s2) { return s1 + ', ' + s2; }
    );
```

This is equivalent to the following code using Flyd and `lift` (note that `intervalStream` doesn't actually exist):

```javascript
var source1 = flyd.map(function(i) { return 'First: ' + i; }, intervalStream(100));
var source2 = flyd.map(function(i) { return 'Second: ' + i; }, intervalStream(150));

var source = flyd.lift(function (s1, s2) { return s1 + ', ' + s2; }, source1, source2);
```

Your second code example, I think, could be written like this:

```javascript
var n1 = stream(1);
var n2 = flyd.map(anotherStream, n1);

flyd.lift(function(x, y) {
  // x is from n1, and y is from anotherStream
}, n1, anotherStream);
```

Am I correct that the rest of your post discusses a function that is not the same as Rx's `combineLatest`?

**Comment by ccorcos** [comment]
I see. You're right. `combineLatest` as RxJS defines it can be achieved with `lift`. What I'm referring to is slightly different. Although, I suppose it could be written like this:

```js
var n1 = stream(1);
var n2 = flyd.switchMap(makeAnotherStream, n1);
var n3 = flyd.lift(args2array, n1, n2)
```

Thus `n2` is a stream created from mapping over `n1`. Then `n3` is the combination of both `n1` and `n2` in parallel... Works for me!

**Comment by paldepind** [comment]
Ok. I think I understand.

I can't think of a good name. But you want something like this:

```javascript
var switchMapWithSrc = function(fn, src) {
  var s = flyd.switchMap(fn, n1);
  return flyd.stream([src, s], function() { return [src(), s()]);
}
```

Then your last example could be written like this:

```javascript
var n1 = stream(1);
var n3 = switchMapWithSrc(makeAnotherStream, n1);
```

We could also have a more general function:

```javascript
function withSrc = function(fn, src) {
  var s = fn(src);
  return flyd.stream([src, s], function() { return [src(), s()]);
}
```

And your example would be:

```javascript
var n1 = stream(1);
var n3 = withSrc(flyd.switchMap(makeAnotherStream), n1);
```

Just some brainstorming.

**Comment by ccorcos** [comment]
Thats exactly what I was thinking!
