### ISSUE TITLE
Non-atomic update of dependent stream created within a dependent stream

### ISSUE THREAD

**Issue by alexgig** [paldepind/flyd#105]
Hi @paldepind,

Let me begin by saying nice work. I've really enjoyed using flyd so far. Thank you for sharing it with us all.

I've come across an edge case that I'm hoping you can help with. I did my best to uncover the cause in the source but had limited success.

Basically, when a dependent stream is created within the body of another stream, and that stream is triggered, the dependent streams dependents are updated twice. I would expect it to be updated only once since the top level stream was only triggered once.

It's hard to describe in words. Here is an example that will allow you to reproduce the unexpected behavior:

``` js
const f = require('flyd');

const input = f.stream(); input.mark = 'input';
const oninput = f.on(v => {
  const s = f.stream(v); s.mark = 's';
  const ds = f.combine(s => s(), [s]); ds.mark = 'ds';
  const dds = f.on(v => console.log('dds:', v), ds); dds.mark = 'dds';
}, input); oninput.mark = 'oninput';
input(0);

// Console output:
//
// dds: 0
// dds: 0
```

From the best I was able to discern, when the oninput body runs, the following streams are added to the global `toUpdate` object: s, ds (not dds).

Then each of those streams have their dependencies updated:
s => updateDeps: ds, dds
ds => updateDeps: dds

Which results in dds being updated twice.

Thoughts?

Thanks for your help!

Best regards,
Alex

**Comment by c-dante** [comment]
By using `flyd.on`, you're forcing anything inside to not be considered a dependency.


A dependent stream can only be created through `combine`, which (under the hood) `map`, `merge`, and `scan` use.


In your example, streams have the following dependencies:
```
input -> oninput === flyd.on end stream

s -> ds

ds -> dds === implicit flyd.on end stream
```

Where `a -> b` means "a is a parent to b" or, "b depends on a".

so, `dds` isn't actually a stream -- it is an "end" stream for the `flyd.on`, `ds` depends only on the created `s` stream.

**Comment by alexgig** [comment]
Hi @c-dante,

Thanks for the reply. I went ahead and refactored the code to use `flyd.map` instead of `flyd.on` and got identical results:

```js
const f = require('flyd');

const input = f.stream();
const oninput = f.combine(input => {
  const s = f.stream(input());
  const ds = f.map(v => {console.log('ds:', v); return s();}, s);
  const dds = f.map(v => console.log('dds:', v), ds);
}, [input]);
input(0);

/**
 * Console output:
 *
 * ds: 0
 * dds: 0
 * dds: 0
 */
```

The example above is simplified in an attempt to highlight the underlying cause of the real issue we are experiencing with the flyd `flatmap` module. 

To give this thread more context, this is a more specific example of what we are really trying to resolve:

```js
const f = require('flyd');
f.flatMap = require('flyd/module/flatmap');

const input = f.stream();
const output = (v) => {
  const s = f.stream(v);
  return f.map(v => v, s);
};
const outputs = f.map(output, input);  // a stream of output streams
const flatOutputs = f.flatMap(s => s, outputs);  // a stream of output values
f.combine(output => console.log('output:', output()), [flatOutputs]);
input(0);

/**
 * Console output:
 *
 * output: 0
 * output: 0
 */
```

In this case, since `input` receives a single value, we expect the flattened stream of output streams to emit a single value. However, we see duplicate values emitted.

**Comment by paldepind** [comment]
Hello @alexgig. Thank you for reporting this bug and contributing a nice example that demonstrates it. This truly is rather peculiar. I've added it as a test and seen the same results that you describe. I hope to take a stab at this soon.

**Comment by alexgig** [comment]
Hello @paldepind,

Thank you.

Best regards,
Alex

**Comment by c-dante** [comment]
Without looking deeper (I'm also curious of what's causing this), I've got a feeling it has to do with the creation of the stream inside an `on` callback -- Making the stream inside the update might be deferring a second update cycle, and since it's appended at the end of the graph, it's probably getting executed once the graph gets there, then again on the second cycle.

Just a thought.

**Comment by anodynos** [comment]
Hello @paldepind - any updates on this issue? 
__________________________________________
PS: I should have started by saying thank you for this great composable FRP lib, so here you go :-) 
I am evaluating it for a new frontend project where Rx would be an overkill and I'm getting hooked to it. 
I really like the fact it plays with well with Ramda and FP principles, fantasy land etc unlike most other established libs. 

With all due respect, I just wanted to know if the project is still alive and maintainable, cause it seems that lately there are serious issues like this one that are just hanging around... 

Kind Regards

**Comment by tinchoz49** [comment]
Hi @paldepind! how are you? 

I start working with flyd and I found the same issue, do you know if is there any update about this? I try to fix it by myself but to be honest I don't understand very well the code and the FRP world is new for me.

I guess that maybe the issue is related with the `updateStream` function and the variable `inStream` but that was all I can get.

Thanks and sorry to bother you.

**Comment by anodynos** [comment]
Any update on this? Since people want to volunteer for a fix, it would be great if we could have even some guidance (things to look for etc), by the author @paldepind :-)

**Comment by garkin** [comment]
Duuude. What a close.
I think, i just [fixed it](https://github.com/garkin/flyd/tree/backport_typescript_fixes).
`npm install https://github.com/garkin/flyd/tarball/backport_typescript_fixes`
