### ISSUE TITLE
why mapping a stream like this?

### ISSUE THREAD

**Issue by ccorcos** [paldepind/flyd#11]
Hey man, you seem to be pretty savvy with functional programming and I'm a newbie, so I was wondering if you could elaborate on your reasoning for this design:

```js

var responses = flyd.stream([urls], function(resp) {
  makeRequest(urls(), resp);
});

var mapStream = function(f, s) {
  return flyd.stream([s], function() {
    return f(s());
  });
};
```

This just seems really odd to me, but maybe it opens up a world of opportunities, I'm just not sure... [I see here how it works though...](https://github.com/paldepind/flyd/blob/master/flyd.js#L76)

**Comment by paldepind** [comment]
I'm not that savvy. Functional programming is a vast topic and there's a lot to learn.

I'm not completely sure what part of the design you don't follow. Can you explain? Then I can give the most concise reasoning for why I've done what I've done.

**Comment by ccorcos** [comment]
It just seems odd that the the second argument to `flyd.stream` is basically a map...

**Comment by paldepind** [comment]
Hm. `mapStream` is supposed to be an implementation of `map`.

In `responses` `makeRequest` is an async function. So it's like a map, except its resolution is delayed and a value is emitted when `makeRequest` calls `resp` with a response.

**Comment by StreetStrider** [comment]
@paldepind, hi. Is it correct that map is sync-only for now? So, if I need an async transform I should construct derived stream via `flyd.stream(deps, fn)`?

@ccorcos, `flyd.stream` can depend on several streams, at the same time, `map` transforms one stream to another. So `map` can be considered as a particular case of `flyd.stream`. No wonder they have similar design (but `flyd.stream` is more general).

**Comment by paldepind** [comment]
@StreetStrider Hello! Thanks to the [promise integration](https://github.com/paldepind/flyd#using-promises-for-asynchronous-operations) you could do it with promises:

```javascript
flyd.map(function(value) {
  return someAsyncOperation(value);
}, aStream);
```

But that is only if your async function returns a promise. If it takes a callback you'll currently have to use `flyd.stream`. But it might be nice to have a convenience function like this:

```javascript
asyncMap(function(value, cb) {
  setTimeout(function() { // Do async stuff
    cb(value * 2);
  }, 20);
}, aStream);
```

**Comment by StreetStrider** [comment]
@paldepind, thanks for the clarification. Promise integration is a really great feature. I've read the secion you've mentioned above, but I didn't got that not only `flyd.stream` can capture promises, but all other functions (like `map`) can do it too. Now it's all clear.

**Comment by paldepind** [comment]
@StreetStrider I really like it as well ;) The promise integration applies to _all_ streams. But I can certainly understand how one could miss that. How do you think the readme could be better at explaining it?

**Comment by StreetStrider** [comment]
@paldepind, I think that could be appropriate. The readme can mention phrase like «all other functions, like `map`, `reduce` support promise integration too.» Or maybe short example:
```js
var request = require('request-promise');

var urls = flyd.stream(…);
var resources = urls.map(function (url) {
  return request(url);
});
```
Something that developer's eye would catch.
