### ISSUE TITLE
NPM module dependencies are outdated

### ISSUE THREAD

**Issue by gcazaciuc** [paldepind/flyd#114]
Hey,

I'm trying to use some flyd modules from NPM  with the latest Flyd lib version but unfortunately it seems they're broken.
Altought in modules folder of Flyd the dependencies seem to be updated to work with the latest API on NPM they're all still using the old API and cannot be used.
Please advise as currently we're stuck on using the vanilla flyd without any usefull modules because of this.

Thanks!

**Comment by paldepind** [comment]
You should use the modules inside the `flyd` package. The individual packages on NPM are no longer supported.
