### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by AlexGalays** [paldepind/flyd#118]
What would be your feeling about including typescript definitions directly inside the repo? 
It's just one `d.ts` file that is linked from the package.json.

**Comment by paldepind** [comment]
That would be splendid. I am using TypeScript myself these days for some projects.

Do you think the main file should cover both the core and the modules? Or should the modules have separate type definitions?

**Comment by AlexGalays** [comment]
If I followed the contrived history of typescript definitions files correctly, then ambient definition files are kind of deprecated right now. That would only leave external modules, i.e a file for each entry point; if they have the same name as the module itself, they should be picked up automatically on import, no need to link the definitions separately.

**Comment by StreetStrider** [comment]
@AlexGalays, so — one file per module, correct?

**Comment by AlexGalays** [comment]
@StreetStrider yes

**Comment by paldepind** [comment]
That sounds correct.

**Comment by dakom** [comment]
Sorry - how is it possible to get typescript to recognize flyd? I don't see any typescript definitions...

**Comment by sdougbrown** [comment]
I've been using flyd in my project and started to put together some definitions for flow.  They could likely serve as a starting point for the typescript defs.  (I'm not personally familiar with writing definitions for ts).

Opened a PR to `flow-typed`, so you can find the types here:
https://github.com/flowtype/flow-typed/pull/951

**Comment by nordfjord** [comment]
#166 adds typescript definitions for flyd and modules.

**Comment by hanneswidrig** [comment]
You should close the issues once they are resolved.
