### ISSUE TITLE
flyd.off(fn, s) ?

### ISSUE THREAD

**Issue by leeoniya** [paldepind/flyd#127]
Hi,

is there a way to unsubscribe a side-effect handler registerd via `flyd.on(fn, s)`.

The situation is this: I have a view layer which renders the stream value on view.redraw(). When that function enconters a stream in its template, it registers itself via flyd.on so that follow-up redraws can be reactive to the stream if it's modified externally. This works fine.

However, on any given redraw this stream may no longer come back in the template, so i must de-register the side-effect handler as the view no longer depends on this stream. How would i do this?

thanks!

**Comment by leeoniya** [comment]
btw, i got around this by simply not using `on` and rather re-creating a self-ending dependent stream on each redraw call. seems like a cleaner solution.

**Comment by c-dante** [comment]
On returns a stream used to end the registration.

```
const debug = flyd.on((x) => console.debug(x));

const s = flyd.stream(0);

const endDebugS = debug(s);

s(0)(1)(2)(3);

endDebugS(true);

s(4)(5)(6);

console.debug(s());
```

**Comment by leeoniya** [comment]
thanks @c-dante , much cleaner.
