### ISSUE TITLE
flyd.js doesn't contain modules

### ISSUE THREAD

**Issue by luminusian** [paldepind/flyd#136]
flyd.js (https://github.com/paldepind/flyd/blob/master/flyd.js) doesn't contain modules like filter (flyd/module/filter).

**Comment by c-dante** [comment]
This is correct -- you need to import what you want from `flyd/modules`

**Comment by luminusian** [comment]
"Flyd works in all ECMAScript 5 environments."
https://github.com/paldepind/flyd#environment-support

However, "import" is FutureReservedWord in ECMAScript 5.1.
https://www.ecma-international.org/ecma-262/5.1/

**Comment by c-dante** [comment]
I don't understand your issue -- if you're not using a module bundler, then you'll need to just declare all the script files you want in your source.

If you are, you require in whatever you need.

```js
const flyd = require('flyd');
flyd.filter = require('flyd/module/filter');
// ...
```

The core `flyd.js` is a minimal library containing only the `stream`, `combine`, `merge`, `map`, and `on` functions, as well as support for the `fantasy-land` spec.

[The built-in modules (filter, obj, filter, etc.) need to be individually required as needed.](https://github.com/paldepind/flyd#modules)
> Modules listed with names in the format flyd/module/filter are builtin to the main flyd module and can be required with require('flyd/module/filter'). Other modules must be installed first with npm.
