### ISSUE TITLE
OnEnd event

### ISSUE THREAD

**Issue by xgrommx** [paldepind/flyd#14]
Hello @paldepind. How can I know when event is ended? For example in Rxjs exists ```onEnd``` callback.

**Comment by paldepind** [comment]
Hello @xgrommx. I'm glad you asked. In Flyd a streams ending is itself a stream that changes to `true` when the stream has ended.

```javascript
var s = flyd.stream();
flyd.map(function() { console.log('s ended'), s.end);
s.end(true); // This ends `s`
```

[There is a section on this in the readme](https://github.com/paldepind/flyd#stream-endings). Please let me know if anything is unclear from the description given there.

**Comment by xgrommx** [comment]
@paldepind thank you for answer. But I don't understand how can I reproduce my code with flyd. This is code:

```js
now = new Date();

Rx.Observable.from(items).map(x => x * x).subscribe((x) => {

}, (e) => {}, () => console.log('Rx', prettyMs(new Date() - now)));
``

**Comment by paldepind** [comment]
Flyd doesn't have a way to create a stream based on an array. I don't know why one would do that. It `items` was a stream you could do this:

```javascript
now = new Date();
var items = flyd.stream();
var squared = flyd.map(x => x * x, items);
flyd.map(() => console.log('Flyd', prettyMs(new Date() - now)), squared.end);
```

**Comment by xgrommx** [comment]
@paldepind As I know list is important thing in functional programming.

**Comment by paldepind** [comment]
@xgrommx I'd say it's important in programming in general. But why would you use a FRP library to operate on a list?

It looks to me like your previous example could just be:

```javascript
var now = new Date();
var squared = _.map(items, x => x * x);
console.log('Rx', prettyMs(new Date() - now));
```
