### ISSUE TITLE
once?

### ISSUE THREAD

**Issue by puppetmaster3** [paldepind/flyd#150]
How do I make a stream 'consumed' once and only once?
Ie, fire even once only no mater how often 'dispatched'

help.

(I'm learning FRP, I checked out 6 FRP libs, I'm going w/ this one for my github projects)

**Comment by tinchoz49** [comment]
hi @puppetmaster3 ! you can do that with the [s.end](https://github.com/paldepind/flyd#stream-endings).

**Comment by tinchoz49** [comment]
haha i noticed that there is already a module https://github.com/bertofer/flyd-once. 

I recomend you to take a look to the modules section: https://github.com/paldepind/flyd#modules

**Comment by puppetmaster3** [comment]
Thx, I saw both, but I am n00b in FRP and .... can't do thos things.
So I did simple things with this lib, like .on().

How would I use end() to do 'once'?
How would I use that module to do 'once'? Also, it was not clear to me how to load the module / like what .js file to load.

**Comment by puppetmaster3** [comment]
reduced to one question
