### ISSUE TITLE
Is flyd interoperable with RxJS / zen-observable?

### ISSUE THREAD

**Issue by andywer** [paldepind/flyd#152]
Hi there!

I like the Ramda/Lodash-ish approach of flyd, but I am still wondering if I can feed it with observables created by RxJS, zen-oberservable & friends.

That would be quite cool :)

**Comment by jlavelle** [comment]
It doesn't seem like a great idea to me, but there are a lot of ways to use them together, if you really want to.  Here's a contrived example:
```
var rxInterval$ = Rx.Observable.interval(1000)
var flydStream$ = flyd.stream()

rxInterval$.subscribe(value => flydStream$(value))

flyd.on(val => {
    console.log(val)
}, flydStream$)
```

**Comment by andywer** [comment]
Thanks for the quick response!
