### ISSUE TITLE
fantasyland/ap works backwards

### ISSUE THREAD

**Issue by schtauffen** [paldepind/flyd#157]
By [spec](https://github.com/fantasyland/fantasy-land#apply) shouldn't `a.ap(b)` be `b.val(a.val)` ?

>A value which has an Apply must provide an ap method. The ap method takes one argument:
>
>a.ap(b)
>b must be an Apply of a function
>
>If b does not represent a function, the behaviour of ap is unspecified.
>b must be same Apply as a.
>a must be an Apply of any value
>
>ap must apply the function in Apply b to the value in Apply a
>
>No parts of return value of that function should be checked.
>The Apply returned by ap must be the same as a and b

**Comment by nordfjord** [comment]
#166 should handle this.

The thing is the argument order is correct for fantasy-land v1. But the argument order changed in a later version of the spec.

Now you can have `F.ap` do whatever you want but `F['fantasy-land/ap']` must follow the spec.

**Comment by paldepind** [comment]
This is fixed now. Prevously Flyd implemented the old Fantasy Land `ap` argument order.
