### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by davidchase** [paldepind/flyd#16]
Really like your approach to FRP, small and easy to use :+1: 

Few questions/findings: 
the example below is from your readme, it seems to be missing a `);` after  `changed.map`
also it seems like `changed` is `undefined` on the initial call rather than `[]` so calling `map` on undefined fails
and i think `s()` should be `s` otherwise throws a error saying `s` is not a function...
```js
var x = flyd.stream(1);
var y = flyd.stream(2);
var sum = flyd.stream([x, y], function(sum, changed) {
  // The stream can read from itself
  console.log('Last sum was ' + sum());
  // On the initial call no streams has changed and `changed` will be []
  changed.map(function(s) {
    var changedName = (s === y ? 'y' : 'x');
    console.log(changedName + ' changed to ' + s());
  }
  return x() + y();
});
```

Also I did 
```js
flyd.isStream(x); // returns true
x.end(true); // throws TypeError
```
however it `x` doesn't seem to have a property `end` on it so i cannot call it?

**Comment by paldepind** [comment]
I'm glad you like the approach :)

Thank you for catching the missing `);`!

The rest of your issues really sounds like you've using an older version of Flyd from before end streams was added and the changed argument turned into an array.

There are tests on the behavior that doesn't work for you and I've just tried executing the examples without any issues.

**Comment by davidchase** [comment]
Ahh you know what it was version `0.1.1` i was playing around with this library on [requirebin](http://requirebin.com/) and for some version it pulled that version instead of `0.1.4`

Sorry about that.

**Comment by paldepind** [comment]
That's quite unfortunate. I'm getting an outdated version as well from requirebin.
