### ISSUE TITLE
endsOn not being curried

### ISSUE THREAD

**Issue by ricardo-devis-agullo** [paldepind/flyd#169]
Why flyd.endsOn [is not curried](https://github.com/paldepind/flyd/blob/bf8defed9b5b17b9df6880cf83af0baa4318d55c/flyd.js#L159)?

Other 2-param functions like [map](https://github.com/paldepind/flyd/blob/bf8defed9b5b17b9df6880cf83af0baa4318d55c/flyd.js#L159), or [merge](https://github.com/paldepind/flyd/blob/bf8defed9b5b17b9df6880cf83af0baa4318d55c/flyd.js#L250) are, so I wonder if there's any reason behind it. I had in my code something like this:

```javascript
const interval$ = R.compose(
  flyd.endsOn(stream$.end),
  flyd.debounceTime(bounceTime || 0),
  flyd.mergeAll
)(sources);
```

And had to convert it to 

```javascript
const interval$ = R.compose(
  stream => flyd.endsOn(stream$.end, stream),
  flyd.debounceTime(bounceTime || 0),
  flyd.mergeAll
)(sources);
```

to make it work. I was thinking of exporting myself a version of endsOn that is curried, but wondered if there's any problem doing that.

Thank you!

**Comment by nordfjord** [comment]
I think it's a hint that it's mutating the stream passed in.

There is a module called takeUntil. But that has its own problems e.g. the argument order is (src, end)

but it does not mutate your stream.

using takeUntil you could do:

```js
const takeUntil = R.flip(require('flyd/module/takeuntil'));

const interval$ = R.compose(
  takeUntil(stream$.end),
  flyd.debounceTime(bounceTime || 0),
  flyd.mergeAll
)(sources);
```

It's also rather curious to see you've extended the flyd object. You could always just

```js
flyd.endsOn = flyd.curryN(2, flyd.endsOn);
```

**Comment by ricardo-devis-agullo** [comment]
Oh, I see, I guess it makes sense. I didn't know that endsOn mutated the stream.

The takeUntil seems to do the trick :)

And yeah, I forgot to mention that I had an extended flyd object :P I don't change already existing methods, but I can always come up with a different name for the flipped takeUntil.

Thanks!

**Comment by nordfjord** [comment]
Closing this as I think takeUntil solves it :smile: Feel free to reopen if you feel this hasn't been resolved properly.
