### ISSUE TITLE
Back-pressure

### ISSUE THREAD

**Issue by zeroware** [paldepind/flyd#17]
How do you handle back-pressure ? 
My use case is that I need to be able to pause stream when they are not processing fast enough.

**Comment by paldepind** [comment]
Currently there are no means to handle back-pressure.

I'm aware of a bunch of different strategies to handle back-pressure. Could you be more specific about what exactly you're looking for? Are there any of the [Rx back-pressure](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/backpressure.md) techniques that solve your use case (to be honest I'm not particularly impressed by those, but many of them would be easy to implement in Flyd)?

**Comment by zeroware** [comment]
I'm working with database change feeds and my use case is that sometimes the processing of change takes time. 
Previously, I used Highland.js to handle it because it allows me to pause the change feed until my processing is done.

**Comment by paldepind** [comment]
So if I understand you want a stream based on some function `producer` and you want the result of that stream consumed by another slower function `consumer`. You want the library to automatically stop calling `producer` when `consumer` can't take the pressure.

What do you expect to happen if `producer` has two dependents and only one of them are slow?

Also, I see that you've asked a [similar question](https://github.com/baconjs/bacon.js/issues/464) on Bacon a while back. Is this something you're asking out of curiosity or is it something that would actually make Flyd useful to you?

**Comment by zeroware** [comment]
> So if I understand you want a stream based on some function producer and you want the result of that stream consumed by another slower function consumer. You want the library to automatically stop calling producer when consumer can't take the pressure.

Yes this is my use case. 

> What do you expect to happen if producer has two dependents and only one of them are slow?

For now I just need the producer to be paused when at least one consumer is slow. 
Maybe after we can think of a buffering system so that fast consumer can continue to process a little while before everything is paused. 

> Also, I see that you've asked a similar question on Bacon a while back. Is this something you're asking out of curiosity or is it something that would actually make Flyd useful to you?

I really like the style of Flyd. I found bacon.js good but very oriented toward UI management.
I also tested RxJS which is a bit complicated. 
I'm using js-csp right now but i'm still looking for a more high-level FRP library :)

**Comment by paldepind** [comment]
Ok. That sounds good :) I think js-csp is a sane choice. But I think FRP is a higher and more powerful abstraction.

I think it would really help me if we could circle in on some pseudo code that would work for you.

This is just from the top of my head:

```javascript
var s = pauseableStream(function(emitCb, doneCb) {
  // do something
  emitCb(something);
});
```

And the function passed to `pauseableStream` would be called as fast as possible as long is it listeners can keep up.

But the above is probably horrible. I'll have to look at how other libraries implements this.

**Comment by zeroware** [comment]
Thanks for your answer. 
You can take a look at Highland.js.

**Comment by paldepind** [comment]
> You can take a look at Highland.js.

I don't see much documentation about how it actually handles back-pressure. And no description about how to create a pauseable source from something that's not a Node Stream.
