### ISSUE TITLE
Compare previous state with current state

### ISSUE THREAD

**Issue by EmirGluhbegovic** [paldepind/flyd#190]
Hey There,

Came from rxjs and Flyd is refreshing. Thank you for making this library.

I have this use case where I am storing the current URL on the state, I am using the Flyd scan and stream functions then to update and send my model state. Is there a way that when I push an update to a stream that I can compare the previous and current state before I fire off an action for example?

I guess a similar function in RxJS would be distinctUntilChanged:
https://www.learnrxjs.io/operators/filtering/distinctuntilchanged.html

Looking for a way of achieving a similar result with Flyd.

Regards,
Emir

**Comment by StreetStrider** [comment]
@EmirGluhbegovic hello. I think it is [drop repeats](https://github.com/paldepind/flyd/tree/master/module/droprepeats). Also, feel free to visit [gitter chat](https://gitter.im/paldepind/flyd).

**Comment by nordfjord** [comment]
@StreetStrider Is absolutely correct, we have the droprepeats module precisely for this usecase.

An example usage would be something along these lines.

```js
import { dropRepeats } from 'flyd/module/droprepeats'
import { stream } from 'flyd'

const s = stream()
const result = [];

s.pipe(dropRepeats).map(val => result.push(val));

s(1)(1)(1)(2)(2)(3)

result // [1, 2, 3]
```

The module also exposes `dropRepeatsWith` with which you can supply your own comparator.

e.g.

```js
import { dropRepeatsWith } from 'flyd/module/droprepeats'
import { equals } from 'ramda'
import { stream } from 'flyd'

const dropRepatsWithEquals = dropRepeatsWith (equals)

const s = stream()
const result = []

s.pipe(dropRepeatsWithEquals).map(val => result.push(val))

s({a: 1})({a: 1})({a: 2})

result // [{a: 1}, {a: 2}]
```

**Comment by EmirGluhbegovic** [comment]
@nordfjord @StreetStrider Thanks for the replies.

The issue I am having is that on a certain model state I fire off an action which updates the model state, the issue being that that causes the "StateChangeListener" to fire off again which then since the state is the same causes the same action to fire off again and so the loop continues .... 

I would want the "StateChangeListener" to be able to compare the previous states state for a certain object value the the new states certain object value and if they differ then run the update action.

Looking at dropRepeat, looks like it will still be stuck in the loop. As the action will fire off which causes the listener to trigger the action etc...

**Comment by StreetStrider** [comment]
@EmirGluhbegovic isn't that custom comparator would suffice for you? Or you need a full historical depth of your state to look in?

**Comment by EmirGluhbegovic** [comment]
@StreetStrider Thanks for getting back so quick.

I only need to compare the most recent state to the previous state.
The part I am a little confused with, (so maybe its my lack of knowledge of Flyd and streams in general), is that there might be different things I want to compare, using the above example would be tricky to implement for different types of "state change listeners" as each needs to compare a different part of the state. I assume the easier way would be in each actual listener to have the comparison done there of prevState vs currentState and then trigger the potential action.

**Comment by EmirGluhbegovic** [comment]
@nordfjord @StreetStrider I have added an example. Please let me know if that makes sense.
I added the example here:
https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA87KAD4AOnQAEU4RAZIJ0mbLCwATmQAO8KWHWwAvOJA54WsKgD0VgK50tAawDmGHriskoATySefSBgAVmAmooJWapo6SiqqGtq6+kYmZhbWdg4ubtwe6kxIDGERUYmxslZY8oqSMoIARtxI3uV19bbw8LxStSpkSMYgiGDwJrXw3loQhgDk7Z28Mz3KhfAMALTzXXSzwCbcOmS8AIwmqD0gB-BHdKdEF1c3AExnD4cnJgC+M72rG1u8dYkewIG6DWxaVYQABK3A6EAAFABKMZ0crQ+xSAAqEBGkgiALRknxWlEOJGUgAagwoLYIOdBGAtAxpP1BogAB6jEDhSLMtERUnE5QEpotfGVPBiTiQGCg3hUdDHACsqCeAHYQJ9CPQmCx0MEqMQeHwIAJ0CaKWQ6GRrjSALJNaBSQxSPZ0cRrDpYc7uz2e2yQdQASSQ5zGRGJowWjjN4ZAJkIUe1UcYADcyM4GNdeL6o57mfAfRdE8mk8phvBzgAGSSfADcwstughUJdUi8vgwI3U8lwyMbdGbUlwTqgYHbncCahZCIRo6Q0EIHaRLtEHfnY6Ry+ttrIDrHy9b2YgSMHkmBQ5z0nUcMQAGVbPVSvUIOoESMT6u-fBh7BbOovZ8AACtmWDtp+iAYOmmbZjcGCFlgg4yDSb7wAi-6AWa8CgUWKIevAYAAO62rA4EYQBQE4WB375r+DCQBclavD+-rwMeiCbouUBrm6vRxDIC7QBglbtkJUAibiugANRSMcyECTIAAkCIzAAxJy8AzEiklclxwmibJxxnvxAm9ux6jSOJClxJ8+FsZ69S9gwjjntGnx0YuJAMLYUBVsmdbCuJYAYLgDBaAit7wo+z4JK+6gmR60gqeplbaW4UBkLAjgIpe8p0Mi7oyGmDDqFIfztipRZkGAOnZvA74zH8mwdNsQIgte2k2VIEAlVACJ-IldnnnQeXXlIHEwneiK0cok36TxhjrkVikjmO0EMBmWbXghYHtiYzEgN1cTmQBVljsdUh2YFdAytAcDXoqIDVqg1brAALAAzK9Wo6iAjDMKwbhgEaXC8Pw8CsFqAC6xCZXQjiKrQ-16qwQQAI50uo3icABBDoGklg2PYTiuO4VgY1j3gAAKfRgdPHFYSA1fAFOY2+3iGpwExTKwpQ6DDxAA-qIAAGIBFIlZakAA

**Comment by nordfjord** [comment]
I see, Looking at the code the big problem seems to be the updateRoute method.

It's mutating the navigation object.

meaning any comparison is futile at that point.

```js
function updateRoute() {
  update(R.assocPath(['navigation', 'path'], 'test'));
}
```

Is equivalent barring the mutation.

If we then add `dropRepeatsWith` to the mix we can create a function `eqPath`

```
const eqPath = R.curry(function(p, v1, v2) {
  const getPath = R.path(p);
  return R.equals(getPath(v1), getPath(v2));
});
```

With that function we can use `dropRepeatsWith` on the state stream

```js
models
  .pipe(dropRepeatsWith(eqPath(['navigation', 'path'])))
  .map(routeSubscriber);
```

[Here's the link](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHhLID4AdNAAl7YwMAE259+AuNQBOEAA7FecadQC8XECWJy4iAPR6ArmjkBrAOb46WPWCgBPYbYfD8AKzgaOLPVNkKxCUkZeUVlNQ0tHX0jEwsrWhtpbGEMLx8-UMCBPUIhUR5+FgAjWmF7bKLiw2Jiel5CiQhhdRBGOGINQuJ7ORhVAHJq2voBhvFU4gwAWmG6tEHgDVoFCHoARg1EBpAV4jW0TcodvYOAJi2T1Y2NAF8BxsmZufppsGNqffpWwzlJmAASrQajAABQASi6aGyAOMvAAKvBOmgfC9oTweCw5BxER1eAA1DBQQwwbYsOByDB8ZqtRgAD06IG8vkp0J82Ix4lRZQqmNypCgHEoIDgMFgnwOCEQIHWAAZEABmADsIFuFHQ2Fw0uE0hW0hgfQwxDg7gQVDoDCYxDwAHcIGhhLQbfgdSsAQahMaAOoQYiEXiqXgAqyGaTSeyg95oCX1V1yd2G72+wigmAARwoSnBvCW4gAbhhpLw5Pq8wBuRr64ihvh2RwJLDFe1gqMxtCguCZ0VQMDZ3NBCBgXiggCE3bARAwcEJUF4AB857wR+mO-gC1BMyWYHnwX3GkFx6v1+CK+Iglu8wGlGuiaegrdGmreMg4ABdE88W7g4XdmBtqUgAALIgACcqrqiAmA4HgprChajDMNKFp4vavoQESACyZRileuZcFMNSENseGdNWorSAAksI2xdJQGKkXUphMDRIAaBQ9FqvRmB5hA5hGgcxH0fhlJ+ixbEcex4jtMQ2yyp+p48Mhii-P8V51q4HT6tgEKnkpvBYNhUBwGpLj4FIVKgqCBnCGKma9gGHC8GAVmGeCmaofsmGGZmKlGjAH5oDwrZfHwuoggAyoYxSZMUMDSB2UyMHugXEHp1ChvqDAAApGv6gYdH5+Dcbx-H0PgImEApxp2ql-qgulYZWjlfrJfh+HUFOMA7NJlwkW11Z-H5Lk2bOqiOf2QQSMhtCwPgUC0OYw1ivg0kBZNEjWct0lXptUArUivAANS8Osd7rbwAAkoIDAAxPSxADOC+0Mkte3bcd6xredVY1vphlnfekIpf1xRaaYVX4Q+wPEDZYAYIYUAyRxn6cnp6bNXlQYhmGEbBQcw5yJm67rETRJnMl-B6eYMDEBjV7BhVoJyF9P3SHwwbpoYRJwKC1O07loLE25vB8xjgtk7up5fgpaC7Z44jlfIYJxgmnpwD6fqpmmYvIAMxV8SFAyZgMFUDO+u6NPgWAYHIoJhYwkXRSEsXSAFhRXbd0mPVYUAQNQpiRh8IUQhNvmMECIIQp+btoHj9Rh4CwKMBCOaNAnoLBlOcC0NQOt6xgPEGwcRu8CbuVm8bXsW2gUM-mKf4hQBCryoBYFqhq0HSlYcBmjQ9AIda0qqq+VC+2gphSqgkGangbhpiS4bCqG5DSlEugGMYZiWNYehzwv9gAAIKvgx-rHowgQB0u-z3F9iwVQPR9HgmQKMPVBQVqIAAGIuLw0mqkAA)

**Comment by EmirGluhbegovic** [comment]
I see it works correctly, but I don't fully understand some of the code. Also what the is R object? Is that reference to Ramda?

If you can run me through the logic that would be very helpful.

Thank you

**Comment by EmirGluhbegovic** [comment]
@nordfjord Thank you, appreciate you taking your time to explain this. 

I want to ask with regards to the curry function, are you using it so that, you automatically are giving it the first parameter with "eqPath(['navigation', 'state'])", then the first time it gets called the "v1" parameter will get called and the second time it gets called the function will have all 3 parameters and therefore run?

If that is the case does that mean then that every subsequent call then fills in the v1 field again and the following the v2 field? Havn't used Ramda or curry time functions, read the docs on ramda.

Want to understand what is exactly happening the background there with the curry function as that part of the eqPath function seems to be the key to the rest of the logic.

**Comment by EmirGluhbegovic** [comment]
@nordfjord thanks for the help, definitely learned something new.
