### ISSUE TITLE
async animations using streams

### ISSUE THREAD

**Issue by ccorcos** [paldepind/flyd#25]
I'm trying to figure out how to do something relatively simple, but using streams.

I have a stream of actions that trigger page transitions, called `routeStream`. When an animation is triggered, no other animations can be triggered while the animation is running. If any actions are emitted from `routeStream` while the animation is running, then when the animation stops, only the most recent action will be animated.

Without really using streams, I can do something like this:

```js
next = null
busy = false
done = function() {
  if (next) {
    n = next
    next = null
    n(done)
  } else {
    busy = false
  }
}
animateLatest = function(f) {
  if (busy) {
    next = f
  } else {
    busy = true
    f(done)
  }
}

flyd.map(function(route) {
  animateLatest(animations[route])
}, routeStream)
```

It seems to me like I should be able to do all of this with streams, but I'm really struggling for some reason...

**Comment by ccorcos** [comment]
Ok. I drew it out to shed some light on it. I'm imagining each animation has its own stream. When a true value is emitted to the stream, it runs the animation and emits false when its done. 

![img_6563](https://cloud.githubusercontent.com/assets/1794527/7664598/62e7bcfa-fb44-11e4-8e53-4dcb442cfdf1.JPG)

Does that make more sense?

**Comment by paldepind** [comment]
So if `routeStream` emits while an animation is in progress you want to save only the last value that was emitted during the animation? For instance in your splendid drawing the last `B` between the two `A`s is discarded right?

Unless I've missed something this looks like what Bacon calls `debounceImmediate`. [Take a look at Bacons version](https://github.com/baconjs/bacon.js#observable-throttle). Is that correct?

How does this look to you? It's untested so it may or may not work ;)

```javascript
var limitRate = function(dur, src) {
  var next, queued = false, busy = false;
  return flyd.stream([src], function(self) {
    if (busy) {
      queued = true;
      next = src();
    } else {
      busy = true
      setTimeout(function() {
        if (queued) {
          queued = false;
          self(next);
        } else {
          busy = false;
        }
      }, dur);
      return src();
    }
  });
}
```

**Comment by ccorcos** [comment]
Close. But I'm dealing with async animation functions -- functions that have one argument that is a callback when the animation is complete.

I have this so far:

queueN will queue up the src stream while any of the busy streams are busy. Queuing 1 is the same as latest and queuing 0 will drop any value emitted while busy,

```
queueN = R.curry (n, busy, src) ->
  q = []
  flyd.stream R.append(src, busy), (self, changed) ->
    srcChanged = R.contains(src, changed)
    isBusy = not R.all(R.eq(false),  R.map((f)->f(), busy))
    if srcChanged
      if isBusy
        q.unshift(src())
        if n >= 0
          while q.length > n
            q.pop()
      else
        self(src())
    else
      if not isBusy
        v = q.pop()
        if v
          self(v)
    return


block = queueN(0)
latest = queueN(1)
queue = queueN(-1)
```

Then I have an animation function defined with a busy stream.

```
animation = (f) ->
  busy = flyd.stream(false)
  animate = (done) ->
    busy(true)
    f ->
      busy(false)
      done?()
  animate.busy = busy
  return animate
```

I can get all the busy streams and queue up the latest route:

```
routeAnimationBusyStreams = R.map(R.prop('busy'), routeAnimations)
animateRouteStream = latest(routeAnimationBusyStreams, routeStream)
```

Then I can execute the proper animation using the following:

```
mapLastTwo = (f, s) ->
  prev = null
  flyd.stream [s], ->
    f(prev, s())

mapLastTwo(handleAnimation, animateRouteStream)
```

This is all quite confusing and convoluted though. I'm not sure I've gained any clarity from using streams here...

**Comment by paldepind** [comment]
Ok. I see. You can't hardcore a duration. You want your animation functions to control when to run, queue and dequeue through the callback they're taking.

I agree that what you've got above is "quite confusing and convoluted". One thing I don't understand about your last example is what the `handleAnimation` function does aed why you need `mapLastTwo`. So I'm not completely sure that what I'm suggesting here will work. But here is my stab at it.

In your first example you had `routeStream` (I'll rename it to `route$` because I like the convention of post-fixing streams with `$`) and `animations`.

```javascript
var animations; // an object/array of animation functions that all takes a callback
var route$; // a stream that emits something that can server as a key to `animations`
```

In your example you did this

```javascript
flyd.map(function(route) {
  animateLatest(animations[route])
}, routeStream);
```

One could do something slightly different:

```javascript
var animationFn$ = flyd.map(function(route) { return animations[route]; });
```

We now have a stream of animation functions. We can now wrap the code in your first example up in a function:

```javascript
var invokeOneAtATimeAndQueueWhenBusy = function(fn$) {
  var nextFn, busy = false;
  function dequeue() {
    if (nextFn) {
      nextFn(dequeue);
      nextFn = undefined;
    } else {
      busy = false;
    }
  }
  flyd.map(function(newFn) {
    if (busy) {
      nextFn = newFn;
    } else {
      busy = true;
      newFn(dequeue);
    }
  }, fn$);
}
```

The code above is almost exactly the same as what you posted in your first example. That's one solution. This does a lot of state mutation and doesn't use streams. So it's not very functional but I'd still say it's better than the stream soup in your last example.

Below however is a functional approach. Notice two things:

1/ We don't mutate any state.
2/ The _only_ "dirty" thing is how we push a value down the `routeAction$` stream in the animation function callback (but this can be made cleaner).
3/ It is very obvious how our state change, what triggers those changes and what those changes depends on.
4/ We only need one additional stream besides `route$`. Having few streams is a good thing!

Please take close look at the example below. If it solves your problem I'll show you how we can make it quite a bit cleaner!

We will have two types of route actions
1/ `{type: 'begin', to: someRoute}` – represents a route request to `someRoute`
2/ `{type: 'done'}` – indicates that the last executed route animation has finished

```javascript
// Map the route stream to a stream of action objects
var routeAction$ = flyd.map(function(route) {
  return {type: 'begin', to: route};
}, route$);

// We scan over `routeAction$` always keeping our state in the accumulator
flyd.scan(function(state, routeAction) {
  if (routeAction.type === 'begin') // User wants to go somewhere
    if (state.busy) {
      return {busy: true, next: routeAction.to}; // Return new state representing the next route
    } else {
      animations[routeAction.to](function() { routeAction$({type: 'done'}); }); // Emit action when done
      return {busy: true, next: undefined}; // We are now busy. No routes queued.
    }
  } else if (routeAction.type === 'done') { // An animation just finished
    if (state.next) { // Is there a queued rout request?
      animations[state.next](function() { routeAction$({type: 'done'}); }); // Go there! Emit when done.
      return {busy: true, next: undefined}; // We are still busy. But the queue is now empty.
    } else {
      return {busy: false, next: undefined}; // Nothing queued. We a no longer busy.
    }
}, {busy: false, next: undefined}, routeAction$);
```

**Comment by ccorcos** [comment]
Wow. Thats much cleaner! Its interesting how you're able to keep the state within the stream as opposed to within a function closure. I like that and it makes a lot of sense. 

So now its time for full disclosure -- what I'm trying to do it a little bit more complicated than this which is probably why I got off on the wrong track. 

Animations can have 4 different relationships to each other:
1) they can be independent
2) they can drop any subsequent animations while busy
3) they can queue up the latest animation while busy
4) they can queue up all subsequent animations while busy

Let me describe why I mean here:

4) These types of animations are good when you're going through a number of scenes like a signup page or welcome/intro page. If you click next 3 times, you will see the next three scenes animate in order. Perhaps there are complicated animations between each scene such that you don't want to drop the second scene.

3) This type of animation is suitable for animations between tabs. If you click a tab and while that page is animating in, you click a bunch of other tabs, then only the latest tab you clicked will animate in next. This is because the animations between tabs tend not to depend on each other.

2) Suppose you have a list view and clicking an item animates to a detail view of that item. Suppose you click one item in the list, then another item before the list view animates off the screen. We want to drop that second action and proceed with animating to the first item detail view.

1) Suppose you have some fancy switches that animate between on and off. If you have multiple switches on a page, then you can click all of them quickly and they'll animate independently of each other.

Now comes the trickiest part. I want to be able to describe these relationships between any animations. For example, (a) while the the welcome pages are animating, I want to drop any tab animations. (b) while animating to the detail view, I want to drop any tab animations. (c) while the switches are animating, I want to queueLatest on any tab animations.

Here's another drawing I made to try to help explain my thinking. The green lines represent the actions / events. The purple arrow represents queueAll. Blue arrows represent queueLatest. Black boxes represent drop. The animation durations are implied by the size of the arrow or box.

![screen shot 2015-05-19 at 2 28 16 pm](https://cloud.githubusercontent.com/assets/1794527/7714436/5e4061b0-fe33-11e4-9ee2-e68dce047210.png)

The method you describe works well for just the tabs stream. But I'm not sure how to represent these more complicated relationships between animations without the state exploding. I was imagining some kind of declarative way of saying "drop animations while other animation is busy" on the streams.

P.S. `route$` has effectively been replaced by `tab$` in the drawing

**Comment by ccorcos** [comment]
OK. So I toyed around with a big monolithic way of doing this. Its interesting, but definitely needs some refactoring. It follows from you example with the addition of a stream key for each action so we know where it came from.

The following achieves the desired functionality between the tab stream and the welcome stream as described in the image above.

```js
var tab$ = flyd.stream()
var welcome$ = flyd.stream()
var animation$ = flyd.merge(tab$, welcome$)


flyd.scan(function(state, action){
  if (action.type === 'begin') {
    if (action.stream === 'welcome') {
      // if beginning a welcome animation
      if (state.welcomeBusy) {
        // queue it up if busy
        var welcomeQueue = R.append(function() {
          welcomeAnimations[action.scene](function() {
            welcome$({type: 'done', stream: 'welcome'});
          }, state.welcomeQueue);
        });
        return R.merge(state, {welcomeQueue: welcomeQueue})
      }
      else {
        // else run the animation
        welcomeAnimations[action.scene](function() {
          welcome$({type: 'done', stream: 'welcome'});
        })
        return R.merge(state, {welcomeBusy: true})
      }
    } else if (action.stream === 'tab') {
      // if beginning a tab animation
      if (state.welcomeBusy) {
        // if welcome is busy, then we want to queue it up until after
        // welcome is done. We'll have to check for next tab on the welcome
        // done event.
        var tabNext = tabAnimation[action.tab](function() {
          tab$({type: 'done', stream:'tab'})
        })
        return R.merge(state, {tabNext: tabNext})
      } else {
        if (state.tabBusy) {
          // if we're busy animating a tab, queue it up next
          var tabNext = tabAnimation[action.tab](function() {
            tab$({type: 'done', stream:'tab'})
          })
          return R.merge(state, {tabNext: tabNext})
        } else {
          // if we're not busy, then run the animation
          tabAnimation[action.tab](function() {
            tab$({type: 'done', stream:'tab'})
          })
          return R.merge(state, {tabBusy: true})
        }
      }
    }
  } else if (action.type === 'done') {
    if (action.stream === 'welcome') {
      if (state.welcomeQueue.length > 0) {
        // if welcome animation is done and there are queued
        // animations, then run one of them
        R.head(state.welcomeQueue)()
        return R.merge(state, {welcomeQueue: R.tail(state.welcomeQueue)})
      } else if (state.tabNext) {
        // else if a tab is queued up next, then run that
        state.tabNext()
        return R.merge(state, {tabNext:null, tabBusy:true, welcomeBusy:false})
      } else {
        // otherwise, we're no longer busy
        return R.merge(state, {welcomeBusy:false})
      }
    } else if (action.stream == 'tab') {
      // if a tab animation is done, run the next one
      // or set to not busy
      if (state.tabNext) {
        state.tabNext()
        return R.merge(state, {tabNext:null})
      } else {
        return R.merge(state, {tabBusy:false})
      }
    }
    return
  }
}, {welcomeBusy:false, welcomeQueue:[], tabBusy:false, tabNext:null}, animation$)
```

**Comment by ccorcos** [comment]
I'm feeling this urge to do something very object oriented using an `Animation` class with a key-value object of animations, and prototype methods `.dropWhen(animation)`, `.queueLatest(animation)`, and `.queueAll(animation)`  to specify relationships between animations.

**Comment by ccorcos** [comment]
Ok. I think I've figured it out. Sorry for all the code -- I really appreciate your advice and suggestions:

The basic idea is to use function composition to pass the action and the state around. The action can be consumed and the state can be updated by each function. In this way, we can define all the animation dependencies.

```js

// animation stream
var animation$ = flyd.stream()

// initial state. each animation has a busy, next and queue
var initialState = {}
var animations = ['tab', 'welcome']
for (var i = animations.length - 1; i >= 0; i--) {
  initialState["#{animations[i]}-busy"] = false
  initialState["#{animations[i]}-next"] = null
  initialState["#{animations[i]}-queue"] = []
};

// drop the action if an animation is busy
var dropOn = R.curry(function(busyAnimation, animation, args) {
  var action = args[0]
  var state = args[1]
  if (action.type === 'begin' && action.stream === animation) {
    if (state[busyAnimation].busy) {
      // consume the action
      return [{}, state]
    }
  }
  return [action, state]
})

// queueLatest an animation if another animation is busy
var queueLatestOn = R.curry(function(busyAnimation, animation, args) {
  var action = args[0]
  var state = args[1]
  if (action.type === 'begin' && action.stream === animation) {
    if (state["#{busyAnimation}-busy"]) {
      var update = {}
      update["#{animation}-next"] = action.func
      // consume the action
      return [{}, R.merge(state, update)]
    } 
  } else {
    if (action.type === 'done' && action.stream === busyAnimation) {
      if (state[animation].next) {
        var update = {}
        update["#{animation}-next"] = null
        update["#{animation}-busy"] = true
        state[animation].next(function() {
          animation$({type:'done', stream:animation})
        })
        return [action, R.merge(state, update)]
      }
    }
  }
  return [action, state]
})

// queue all animations if another animation is busy
var queueAllOn = R.curry(function(busyAnimation, animation, args) {
  var action = args[0]
  var state = args[1]
  if (action.type === 'begin' && action.stream === animation) {
    if (state["#{busyAnimation}-busy"]) {
      var update = {}
      update["#{animation}-queue"] = R.append(action.func, state["#{animation}-queue"])
      // consume the action
      return [{}, R.merge(state, update)]
    } 
  } else {
    if (action.type === 'done' && action.stream === busyAnimation) {
      if (state["#{animation}-queue"].length > 0) {
        var update = {}
        update["#{animation}-busy"] = true
        update["#{animation}-queue"] = R.tail(state["#{animation}-queue"])
        R.head(state["#{animation}-queue"])(function() {
          animation$({type:'done', stream:animation})
        })
        return [action, R.merge(state, update)]
      }
    }
  }
  return [action, state]
})

var queueAllOnWelcome = queueAllOn('welcome')
var dropOnWelcome = dropOn('welcome')
var queueLatestOnTab = queueLatestOn('tab')



flyd.scan(function(state, action){
  var handleAction = R.compose(
    queueAllOnWelcome('welcome'),
    dropOnWelcome('tab'),
    queueLatestOnTab('tab')
  )
  var args = [state, action]
  var result = handleAction(args)
  action = result[0]
  state = result[1]

  // the action can be consumed by handleAction
  // if its not consumed, then we can run the animation
  // or set busy to false
  if (action.type === 'begin') {
    action.func(function() {
      animation$({type:'done', stream:action.stream})
    })
    var update = {}
    update["#{action.stream}-busy"] = true
    state = R.merge(state, update)
  } else if (action.typr === 'done') {
    var update = {}
    update["#{action.stream}-busy"] = false
    state = R.merge(state, update)
  }

  return state
}, initialState, animation$)

```

Does this make sense? Is this going to be sane? Any considerations?

Thanks

**Comment by paldepind** [comment]
Why are you using dynamic property names? You have something like this

```javascript
var initialState = {
  'tab-busy': false,
  'tab-next': null,
  'tab-queue': [],
  'welcome-busy': false,
  'welcome-next': null,
  'welcome-queue': [],
};
```

Why not this instead?

```javascript
var initialState = {
  tab: {busy: false, next: [], queue: []},
  welcome: {busy: false, next: [], queue: []},
};
```

Why are you creating `handleAction` inside the `scan`? Why not just:

```javascript
var handleAction = R.compose(
  queueAllOn('welcome', 'welcome'),
   dropOn('welcome', 'tab'),
  queueLatestOn('tab', 'tab')
)
```

If find the name `action.stream` to be confusing. It's not a stream right? But instead the name of an animation type.

I like your approach here. There are a bit of repetition but I think it could be refactored into a really nice solution.

**Comment by ccorcos** [comment]
> Why not this instead?
> 
> ```js
> var initialState = {
>   tab: {busy: false, next: [], queue: []},
>   welcome: {busy: false, next: [], queue: []},
> };```

I originally had that, but I wasn't sure if R.merge is deep like that. Regardless, I could make my own merge function if necessary. This is definitely the better way of doing it.

> Why are you creating handleAction inside the scan?

You're right.

> If find the name action.stream to be confusing. It's not a stream right? But instead the name of an animation type.

Yes, now we have type and type. I'll think about it...

> Why are there a queue for each animation type? Why is that necessary?

You never know what animations are going to queueAll, or queueLatest other animations. Giving every animation type its own next and queue state is a way to ensure you can create whatever relationships your want between animations.

> I like your approach here. There are a bit of repetition but I think it could be refactored into a really nice solution. If you take a stab at it please post it here. I'd like to take a look and maybe take a second stab ;)

Thats good to hear! I'll give it another go. How do you feel about coffeescript by the way?

**Comment by paldepind** [comment]
> I originally had that, but I wasn't sure if R.merge is deep like that. Regardless, I could make my own merge function if necessary. This is definitely the better way of doing it.

No `R.merge` is not deep. [But this function is coming](https://github.com/ramda/ramda/pull/1088) which is like a deep `R.merge`. But you could also use `R.assocPath`.

> Thats good to hear! I'll give it another go.

Be sure to share it :+1:

> How do you feel about coffeescript by the way?

Mixed feelings. I did use it at one point but since the arrival of great ECMAScript 6 transpilers I prefer to use it instead.

**Comment by ccorcos** [comment]
> Mixed feelings. I did use it at one point but since the arrival of great ECMAScript 6 transpilers I prefer to use it instead.

I came from python so I really appreciate not having to use {} everywhere!


Anyways, here's where I am so far.

```coffee
###
state = {
  animationName: {
    busy: true or false
    next: func or null
    queue: [] or [func, ...]
  }
}

action = {
  type: 'begin' or 'end'
  animation: animationName
  func: func
}

all functions here have a done callback as the first and only arguement
###


# The animatino stream
animation$ = flyd.stream()

animationNames = ['tab', 'welcome']

# the initial state of the animation$ scan
# point free?
initialState = {}
for name in animationNames
  initialState[name] = {busy:false, next:null, queue:[]}


# drop the action if an animation is busy
dropOn = R.curry (busyAnimation, animation, {action, state}) ->
  if action.type is 'begin' and action.animation is animation
    if state[busyAnimation].busy
      # drop the animation by consuming the action
      action = {}
  return {action, state}


# queueLatest an animation if another animation is busy
queueLatestOn = R.curry (busyAnimation, animation, {action, state}) ->
  if action.type is 'begin' and action.animation is animation
    if state[busyAnimation].busy
      # queue up the next animation
      state = R.assocPath([animation, 'next'], action.func, state)
  else
    if action.type is 'end' and action.animation is busyAnimation
      func = state[animation].next
      if func 
        state = R.compose(R.assocPath([animation, 'next'], null),
                          R.assocPath([animation, 'busy'], true))(state)
        # start the next animation
        func -> animation$({type: 'end', animation})
  return {action, state}

# queue all animations if another animation is busy
queueAllOn = R.curry((busyAnimation, animation, {action, state}) ->
  if action.type is 'begin' and action.animation is animation
    if state[busyAnimation].busy

      # ugly
      state = R.converge(
        R.assocPath([animation, 'queue']), 
          R.compose(
            R.append(action.func),
            R.path([animation, 'queue'])
          ), 
          R.identity
        )(state)

        # consume the action
        action = {}
  else
    if action.type is 'end' and action.animation is busyAnimation
      if state[animation].queue.length > 0
        func = R.head(R.assocPath([animation, 'queue']))
        
        # ugly
        state = R.compose(
          R.assocPath([animation, 'busy'], true),
          R.converge(
            R.assocPath([animation, 'queue']),
            R.compose(R.tail, R.assocPath([animation, 'queue'])),
            R.identity
          )
        )(state)

        func -> animation$({type: 'end', animation})
  return {action, state}
```

I left a few comments `# point free?` and `# ugly`. Not sure how to fix those up. I could definitely create those functions outside though.

I'm trying to figure out how to refactor this more though... I've started to do something like this, but it looks terrible.

```coffee
beginAndBusy = R.curry (busyAnimation, animation, action, state) ->
  R.allPass([R.propEq('type', 'begin', action), R.propEq('animation', animation, action), R.propEq(busyAnimation, 'busy', state)])
  
enqueue = R.curry (animation, action) ->
  R.converge(
    R.assocPath([animation, 'queue']), 
      R.compose(
        R.append(action.func),
        R.path([animation, 'queue'])
      ), 
      R.identity
    )

# queue all animations if another animation is busy
queueAllOn = R.curry((busyAnimation, animation, {action, state}) ->
  if R.call(beginAndBusy, arguments)
    state = enqueue(animation, action)(state)
    # consume the action
    action = {}
  else
    if action.type is 'end' and action.animation is busyAnimation
      if state[animation].queue.length > 0
        func = R.head(R.assocPath([animation, 'queue']))
        # ugly
        state = R.compose(
          R.assocPath([animation, 'busy'], true),
          R.converge(
            R.assocPath([animation, 'queue']),
            R.compose(R.tail, R.assocPath([animation, 'queue'])),
            R.identity
          )
        )(state)

        func -> animation$({type: 'end', animation})
  return {action, state}
```

**Comment by ccorcos** [comment]
the rest:

```coffee
# the order of these function is important because actions can be consumed.
# its best to put drop first, then queueLatest, and then queueLatest
handleAnimation = R.compose(
  queueAllOn('welcome', 'welcome')
  queueLatestOn('tab', 'tab')
  dropOn('welcome', 'tab')
)


flyd.scan ((state, action) ->
  {state, action} = handleAction({state, action})

  # the action can be consumed by handleAction
  # if its not consumed, then we can run the animation
  # or set busy to false
  if action.type is 'begin'
    {func, animation} = action
    func -> animation$({type: 'end', animation})
    state = R.assocPath([animation, 'busy'], true, state)
  else if action.type is 'end'
    state = R.assocPath([animation, 'busy'], false, state)

  return state
), initialState, animation$

```

**Comment by ccorcos** [comment]
Ok, I got the initial state in a point free way.
```coffee
initAnimState = R.flip(R.assoc(R.__, {busy:false, next:null, queue:[]}, R.__))
state = R.reduce(initAnimState, {}, animationNames)
```

**Comment by ccorcos** [comment]
this just feels like overkill now.  Any refactoring suggestions? Otherwise, I'm going to stick with what I had before and test it all out

```


beginBusy = (busyAnimation, animation, {action, state}) ->
  R.allPass([
    R.propEq('type', 'begin', action)
    R.propEq('animation', animation, action)
    R.path([busyAnimation, 'busy'], state)
  ])

busyEnd = (busyAnimation, animation, {action, state}) ->
  R.allPass([
    R.propEq('type', 'end', action)
    R.propEq('animation', busyAnimation, action)
  ])

startAnimation = (animation, func) ->
  func -> animation$({type: 'end', animation})


# drop the action if an animation is busy
dropOn = R.curry (busyAnimation, animation, {action, state}) ->
  if R.call(beginBusy, arguments)
    # drop the animation by consuming the action
    action = {}
  return {action, state}


# queueLatest an animation if another animation is busy
queueLatestOn = R.curry (busyAnimation, animation, {action, state}) ->
  if R.call(beginBusy, arguments)
    # queue up the next animation
    state = R.assocPath([animation, 'next'], action.func, state)
  else if R.call(busyEnd, arguments)
      func = state[animation].next
      if func 
        state = R.compose(R.assocPath([animation, 'next'], null),
                          R.assocPath([animation, 'busy'], true))(state)
        # start the next animation
        startAnimation(animation, func)
  return {action, state}

# queue all animations if another animation is busy
queueAllOn = R.curry((busyAnimation, animation, {action, state}) ->
  if R.call(beginBusy, arguments)
    state = R.converge(
      R.assocPath([animation, 'queue']), 
        R.compose(
          R.append(action.func),
          R.path([animation, 'queue'])
        ), 
        R.identity
      )(state)

    # consume the action
    action = {}

  else if R.call(busyEnd, arguments)
    if state[animation].queue.length > 0
      func = R.head(R.assocPath([animation, 'queue']))
      
      # ugly
      state = R.compose(
        R.assocPath([animation, 'busy'], true),
        R.converge(
          R.assocPath([animation, 'queue']),
          R.compose(R.tail, R.assocPath([animation, 'queue'])),
          R.identity
        )
      )(state)

      startAnimation(animation, func)
  return {action, state}


# the order of these function is important because actions can be consumed.
# its best to put drop first, then queueLatest, and then queueLatest
handleAnimation = R.compose(
  queueAllOn('welcome', 'welcome')
  queueLatestOn('tab', 'tab')
  dropOn('welcome', 'tab')
)


flyd.scan ((state, action) ->
  {state, action} = handleAction({state, action})

  # the action can be consumed by handleAction
  # if its not consumed, then we can run the animation
  # or set busy to false
  if action.type is 'begin'
    {func, animation} = action
    startAnimation(animation, func)
    state = R.assocPath([animation, 'busy'], true, state)
  else if action.type is 'end'
    state = R.assocPath([animation, 'busy'], false, state)

  return state
), initialState, animation$
```

**Comment by paldepind** [comment]
Right now I don't really understand the logic behind when an action should be consumed and in which cases you want several handlers to operate on the same action? I have another idea for a refactor but it may or may not work. That fall through behavior makes it hard to tell what exactly is going on.

What I've done below: Split things into more functions for readability, reuse and for getting rid of mutations. The code in the `scan` still mutates which is ugly. As far as I can tell updating `busy` as you do right after you "# ugly" comment is unnecessary. The state should already be busy when an animation ends.

```coffeescript
initAnimState = R.flip(R.assoc(R.__, {busy:false, next:null, queue:[]}, R.__))
initialState = R.reduce(initAnimState, {}, animationNames)

beginBusy = (busyAnimation, animation, action, state) ->
  R.and(R.where({type: 'begin', animation: animation}, action),
        R.path([busyAnimation, 'busy'], state));

busyEnd = (busyAnimation, action) ->
  R.where({type: 'end', animation: busyAnimation}, action);

startAnimation = (animation, func) ->
  func -> animation$({type: 'end', animation})

consumeAction = ({action, state}) -> {action: {}, state: state};

# set the next animation
setNext = (animation, func, data) ->
  R.assocPath(['state', animation, 'next'], action.func, data)

# run and drop the next animation
startNext = (animation, state) ->
  nextFunc = state[animation].next
  if nextFunc startAnimation(animation, nextFunc)
  R.compose(R.assocPath([animation, 'next'], null),
            R.assocPath([animation, 'busy'], true))(state)

# append an animation function to the queue
enqueue = (animation, func, data) ->
  # could be better if Ramda was better at nested objects
  newQueue = R.append(func, data.state[animation].queue);
  R.evolve({state: R.assocPath([animation, 'queue'], newQueue)}, data);

# run and drop the firt queued animation
dequeue = (animation, state) ->
  nextFunc = R.head(state[animation].queue)
  if nextFunc startAnimation(animation, nextFunc)
  newQueue = R.tail(state[animation].queue);
  R.assocPath([animation, 'queue'], newQueue, state)

# drop the action if an animation is busy
dropOn = R.curry (busyAnimation, animation, {action, state}) ->
  if beginBusy(busyAnimation, animation, action, state)
    consumeAction({action, state})
  else
    {action, state}

# queueLatest an animation if another animation is busy
queueLatestOn = R.curry(busyAnimation, animation, {action, state}) ->
  if beginBusy(busyAnimation, animation, action, state)
    setNext(animation, action.func, {action, state})
  else if busyEnd(busyAnimation, action)
    {action, state: startNext(animation, state)}

# queue all animations if another animation is busy
queueAllOn = R.curry((busyAnimation, animation, {action, state}) ->
  if beginBusy(busyAnimation, animation, action, state)
    consumeAction(enqueue(animation, action.func, {action, state})
  else if busyEnd(busyAnimation, action)
    {action, state: dequeue(animation, state)}

# the order of these function is important because actions can be consumed.
# its best to put drop first, then queueLatest, and then queueLatest
handleAnimation = R.compose(
  queueAllOn('welcome', 'welcome')
  queueLatestOn('tab', 'tab')
  dropOn('welcome', 'tab')
)

flyd.scan ((state, action) ->
  {state, action} = handleAction({state, action})

  # the action can be consumed by handleAction
  # if its not consumed, then we can run the animation
  # or set busy to false
  if action.type is 'begin'
    {func, animation} = action
    startAnimation(animation, func)
    state = R.assocPath([animation, 'busy'], true, state)
  else if action.type is 'end'
    state = R.assocPath([animation, 'busy'], false, state)

  return state
), initialState, animation$
```

**Comment by ccorcos** [comment]
> I don't really understand the logic behind when an action should be consumed and in which cases you want several handlers to operate on the same action?

Anytime you enqueue an animation because another animation is busy and blocking it, then the animation is effectively consumed. If an action isn't consumed, then it is invoked.

> As far as I can tell updating busy as you do right after you "# ugly" comment is unnecessary. The state should already be busy when an animation ends.

Not quite. If an animation queues itself like `queueOn('welcome', 'welcome')` then you're correct. But if you have  `queueOn('tab', 'welcome')` as well, then welcome may not be busy, and when `tab` finishes, then it will start the first queued welcome animation. 

------------------------------------

R.evolve is super cool! I like the way you broke down every function into smaller pieces. Its annoying having to pass arguments around to much, but it makes sense... 

There are some edge cases here in which the 3 functions we defined won't entirely work as expected, for example:
- if an animation X queues another animation Y that doesnt queue itself, then only the first Y animation in the queue will run when X finishes. This could be solved with some extra code
- if an animation X queues two other animations, Y and Z, and Y and Z queue each other, then when X finishes, either Y or Z will run first depending on the order they're composed. In the following order, the Z animation queue will clear before the Y animation queue

```
handleAnimation = R.compose(
  queueAllOn('X', 'Y')
  queueAllOn('X', 'Z')
  queueAllOn('Y', 'Z')
  queueAllOn('Z', 'Y')
)
```

But what I really like about using `flyd.scan` like we do here is we can define whatever complicated animation relationships we want and just compose them into the `handleAnimation` pipeline. :) So I'm not so worried about these edge cases right now.

Anyways, to interact with this, I simply have a function:

```
enqueueAnimation = (animation, func) -> animation$({type:'begin', animation, func})`
```

Then, write the handleAnimation function composition however I need. This is pretty sweet!

Any final thoughts? I'll let you know how it goes when I get it working in my web app. Thanks so much for the help!
