### ISSUE TITLE
curryN code duplication

### ISSUE THREAD

**Issue by queckezz** [paldepind/flyd#27]
I peaked into the source of flyd today. One thing I noticed that there is a curryN [implementation](https://github.com/paldepind/flyd/blob/master/flyd.js#L279-L385) which seems to be exactly the same as the one from ramda. If one uses ramda already, there is quite some code duplication.

Why did you choose to copy it into source instead of requiring the function? If it's an altered version maybe there's potential to merge it back into ramda?
```js
var curryN = require('ramda/src/curryN')
```

Also I think the boilerplate in the source belongs to a build step:
```js

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define([], factory); // AMD. Register as an anonymous module.
  } else if (typeof exports === 'object') {
    module.exports = factory(); // NodeJS
  } else { // Browser globals (root is window)
    root.flyd = factory();
  }
}(this, function () {
```
We could use something like browserify to make a final bundle for those who aren't using `require()` on the client and distribute that:
```bash
browserify lib/index.js --standalone > flyd.js
```

Just my 2¢! All in all a seriously awesome library :) I'm also looking forward to play around with `snappdom` ;)

**Comment by StreetStrider** [comment]
@queckezz, for such kind of situations the main reason is trying to keep this state of `package.json`:
```js
  "dependencies": {
  },
```
:)

**Comment by paldepind** [comment]
I guess you missed this comment:

```javascript
// Own curry implementation snatched from Ramda
// Figure out something nicer later on
```

;)

I did that to keep the dependencies at zero like @StreetStrider suggested. Depending directly on Ramda's `curryN` [like I've done here](https://github.com/paldepind/union-type-js/blob/master/union-type.js#L1) and doing a nice browser build is on my todo list!

In other words I agree with you! I'll take a look at the `--standalone` option for browserify. It sounds like exactly what we'd need!
