### ISSUE TITLE
Stream callback needs to provide the dependant streams in arguments

### ISSUE THREAD

**Issue by sporto** [paldepind/flyd#3]
Consider your example:

```
var x = flyd.stream(4);
var y = flyd.stream(6);
var sum = flyd.stream([x, y], function() {
  return x() + y();
});
```

Now how would you break this in modules?

```
var callback = require('./callback');

var x = flyd.stream(4);
var y = flyd.stream(6);

var sum = flyd.stream([x, y], callback);
```

// callback.js

```
module.exports = function(self, changed) {
	// how would you get x and y here?
  return x() + y();
}
```

**Comment by paldepind** [comment]
That is a very good question! You're indeed right that the function passed to `flyd.stream` needs to have its dependents in scope to be of much use. But let me show you why I think that actually isn't a real issue.

The documentation sadly doesn't explain this properly (sorry), but `flyd.stream` is considered _only_ to be the low level building block of Flyd. You should use `flyd.stream` to create modules for Flyd – but nothing else. `flyd.stream` is a meant to be a powerful way to implement new abstractions in modules.

This is how I would use it to tackle the problem in your specific example. First of all, note the following things about the function you're exporting in `callback.js`:

1. It actually doesn't need access to `self` and `changed`.
2. It operates on two streams.
3. The function would be more naturally expressed as a function taking two arguments: `function(x, y) { return x + y; }`

Now, what if we had an abstraction that allowed us to apply a function taking two arguments to two streams and get a new stream? Such that we could simply define the exported function as above and invoke it with the two streams. Building this abstraction with `flyd.stream` is very easy:

```javascript
module.exports = function(fn, stream1, stream2) {
  return flyd.stream([stream1, stream2], function() {
    return fn(stream1(), stream2());
  });
};
```

With this function your example would be implemented like this:

// callback.js
```javascript
module.exports = function(x, y) {
  return x + y;
}

// index.js
```javascript
var lift2 = require('./lift2'); // The function defined above
var callback = require('./callback');

var x = flyd.stream(4);
var y = flyd.stream(6);

var sum = lift2(callback, x, y);
```

A more general function like the above would work with functions taking any number of arguments. Such a function is implemented in the module [flyd-lift](https://github.com/paldepind/flyd-lift).

I hope the above explanation makes sense to you. Do you still think it is a problem that the callback to `flyd.stream` needs to have its dependent streams in scope? It hasn't been a problem for me so far but you might see something I've missed. If is actually is a problem then passing the dependent streams to the callback after `self` and `changed` might be the solution.

If you have any ideas about how I could make the documentation clearer and more easy to understand please let me know :)

**Comment by paldepind** [comment]
Oh, and btw: When I say that `flyd.stream` is primarily for implementing modules I only mean the `stream(dependencies, fn)` variant. `flyd.stream(constant)` should generally be used for creating what I refer to as "top level" streams in the tutorial.

**Comment by sporto** [comment]
Not really sure if this is a problem to be honest, I posted the issue because this jumped to my attention when reading the readme. Feel free to close it.

**Comment by paldepind** [comment]
Ok. I will keep it in mind but for now I don't think this is an actual problem.

**Comment by jayrbolton** [comment]
> Oh, and btw: When I say that flyd.stream is primarily for implementing modules I only mean the stream(dependencies, fn) variant. flyd.stream(constant) should generally be used for creating what I refer to as "top level" streams in the tutorial.

@paldepind I found this issue after having some of these same questions and seeing other people react skeptically when I showed them the readme. 

I agree it's not an actual problem as a low-level utility function, but I might suggest that we simply move its description down to the bottom of the readme under a section such as "Creating Modules" or "Extending Functionality", and instead put examples for higher level abstractions like `map`, `merge`, `lift`, etc at the top.

**Comment by paldepind** [comment]
@jayrbolton 

I think that is made clear in the readme:

>This is not a demonstration of how you would write code with Flyd on a day to day basis. For that take a look at the examples.

>This tutorial will however introduce you to the minimal but powerful core that Flyd provides and show you how it can be used to build FRP abstractions.

But your suggestion about adding examples at the top.
