### ISSUE TITLE
Bower registry

### ISSUE THREAD

**Issue by yuretz** [paldepind/flyd#46]
Hej paldepind,

Awesome stuff! Love your minimalistic and modular approach.

Are you going to register flyd on bower any time soon?

Vh, Yuriy

**Comment by paldepind** [comment]
Hej yuretz,

I'm really glad you like it!

I've just registered the latest version of Flyd on Bower :)

Are you a dane? Nordic? I'm asking because of your "hej" and "vh"?

**Comment by yuretz** [comment]
Thanks!

No, I'm neither Dane nor Nordic, but I live in Denmark in the southern part of Jylland. So I've just looked at your profile and figured out it would be OK to greet you in Danish :)

BTW, do you know if flyd has ever been used in production?
