### ISSUE TITLE
(Possible) Unused variable in flyd.js, L163

### ISSUE THREAD

**Issue by stieizc** [paldepind/flyd#53]
Hi all,
Thank you for making such a great library! It's so small, yet so capable.
I came across the code for createStream() in flyd.js, [line 163](https://github.com/paldepind/flyd/blob/0c8a890792f9ba8d45758fd0144317a99577a9e0/flyd.js#L163), and found that `i` and `list` is not uses by the function, nor are they bound to `this`. I'm quite new to js, and frequently get confused with `this`, so maybe I got it wrong.
Thank you in advance.

**Comment by StreetStrider** [comment]
@stieizc, giving links to master's lines is not a good idea, since master is volatile as almost any branch. [same line on certain revision](https://github.com/paldepind/flyd/blob/0c8a890792f9ba8d45758fd0144317a99577a9e0/flyd.js#L163)

**Comment by raine** [comment]
(You can press `y` on the page to get a link to the specific revision.)

**Comment by paldepind** [comment]
Yep. It seems like they've been made unnecessary by a refactor without having been taken out.

I'm on vacation right now. I'll fix it when I get home. A PR will also be accepted!

**Comment by stieizc** [comment]
@StreetStrider Changed the link accordingly, didn't thought about that.
@raine Didn't know that github has shortcuts too, like gmail.
@paldepind Thank you for your response, have a nice vacation:)

**Comment by benji6** [comment]
fwiw there's also an unused `i` declared here: https://github.com/paldepind/flyd/blob/0dd21bdcd3d080e6fdb22388fff6b68d5228e8fe/lib/index.js#L191
Awesome library btw :)

**Comment by paldepind** [comment]
@benji6 Great catch! I've taken it out :)
