### ISSUE TITLE
merge multiple

### ISSUE THREAD

**Issue by jethrolarson** [paldepind/flyd#66]
I was banging my head against a problem for a while before realizing that flyd.merge is binary. For some reason I expected it to merge all arguments. 

flyd.merge(a, b, c)

I wish js would throw on these kind of errors...

I guess this is more feedback than a bug. Close if you think it's not a problem.

**Comment by paldepind** [comment]
What about adding a `mergeAll`? It takes a list of streams and merges them all?

**Comment by jethrolarson** [comment]
Seems reasonable.

**Comment by ccorcos** [comment]
I was just thinking this... We could also use a clone.

```js
flyd.clone = function(s) {
  return flyd.stream([s], function() { 
    return s()
  })
}

flyd.mergeAll = function(list) {
  if (list.length === 0) {
    return flyd.stream()
  } else if (list.length === 1) {
    return flyd.clone(list[0])
  } else {
    return R.reduce(flyd.merge, list[0], list.slice(1))
  }
}
```

**Comment by jordalgo** [comment]
I was also just looking for something like this. :+1:

**Comment by jordalgo** [comment]
here is a quick attempt: https://github.com/paldepind/flyd/pull/79

**Comment by paldepind** [comment]
This issue is solved thanks to the `mergeAll` module contributed by @jordalgo.
