### ISSUE TITLE
How do you do error handling when using Flyd?

### ISSUE THREAD

**Issue by kwijibo** [paldepind/flyd#69]
For example, if you create a stream from a Promise, and the promise rejects, it seems like the error is just swallowed up? 

When programming with flyd, what do you do with errors from callback-based APIs?

**Comment by ericgj** [comment]
See #35 - seems there was a proposal to use Eithers but nothing has happened with it yet. In the meantime there are some workarounds mentioned in that thread.

**Comment by kwijibo** [comment]
Thanks @ericgj
