### ISSUE TITLE
Autocurry flyd.filter

### ISSUE THREAD

**Issue by ccorcos** [paldepind/flyd#70]
Why aren't all the methods auto-curried?

```js
  R.pipe(
    R.curry(flyd.map)(R.prop('outbox'))
    R.curry(flyd.filter)(nonEmpty)
    R.curry(flyd.on)(R.map(send(receive$)))
  )(model$)
```
Oy vey.

**Comment by paldepind** [comment]
Both `map` and `on` are curried?

`filter` is a mistake.

**Comment by ccorcos** [comment]
Ah, you're right. Filter isnt -- thats what let me to think none of them were.

**Comment by paldepind** [comment]
I've just pushed a new version to npm that should include a curried filter.

**Comment by ccorcos** [comment]
awesome
