### ISSUE TITLE
Using flyd.on returns undefined instead of a stream

### ISSUE THREAD

**Issue by qur2** [paldepind/flyd#72]
I'm using flyd along with React and I'm trying to get rid of one of its warning. Basically, I found out that I may have some kind of race condition and therefore decided to manually clean up all streams when a component unmounts.

Long story short: `flyd.on()` returns `undefined` instead of a stream that I could then close. Did I miss something or is that a real issue?

```javascript
var s1 = f.stream()
var s2 = f.on(function(x) {console.log(x)}, s1)
s1
stream(undefined)
s2
undefined
s2.end
VM26253:1 Uncaught TypeError: Cannot read property 'end' of undefined(…)
```

Thanks for the library, I've been playing with the RxJS and likes, and this one is much easier to get into!

**Comment by kedashoe** [comment]
Hello @qur2 , I believe this was addressed in #64, but has not yet made it into a release.

**Comment by qur2** [comment]
Ok, thanks, didn't see that one. In the meantime I'm using .map().

**Comment by paldepind** [comment]
I've pushed a new version to npm which includes a fix to this issue.
