### ISSUE TITLE
Whats new in 0.2?

### ISSUE THREAD

**Issue by ccorcos** [paldepind/flyd#76]
No History.md?

**Comment by c-dante** [comment]
https://github.com/paldepind/flyd/pull/71
----

Summary:
* Fixed `flyd/module/scanmerge`
* Removed dependent stream syntax `flyd.stream([streams], combinFn)` in favor of a dedicated combine

```
var add = (a, b) => a + b;
var addCombine = flyd.combine(add);
var b = flyd.stream(0);
var a = flyd.stream(0);
var aPlusB = addCombine([a, b]);
```

The full signature is:
```
flyd.combine((depA, depB, ..., depN, self, changed) => *, [depA, depB, ..., depN]);
```

Where `self` is the combined stream and `changed` is an array of streams that have changed (subset of `depA, depB, ...`.

If the combine function will update the stream if it returns anything but `undefined`, to set the value to undefined use `self(undefined);` to update.

**Comment by ccorcos** [comment]
Sweet. Thanks! Interesting. Is `flyd.stream([streams], combinFn)` entirely removed or just discourages in favor of combine?

**Comment by c-dante** [comment]
Entirely removed

**Comment by ccorcos** [comment]
I see. Any thoughts on a Changelog?

**Comment by c-dante** [comment]
@paldepind, do you have a changelog / history? Would be good to add them with future releases. What are your thoughts?

**Comment by ccorcos** [comment]
I think simply putting your response to this ticket in a file called HISTORY.md would suffice. Just some place to notify me. :)

**Comment by paldepind** [comment]
I've added a changelog `HISTORY.md` based on @c-dante's response :smile:
