### ISSUE TITLE
takeUntil

### ISSUE THREAD

**Issue by ccorcos** [paldepind/flyd#9]
http://reactivex.io/documentation/operators/takeuntil.html

**Comment by paldepind** [comment]
I've looked at both Rx and Bacon. They both have a function named `takeUntil` but with the slight difference that the observable returned by Rx ends if the second observable ends. In Bacons implementation the returned stream doesn't end if the second stream ends without ever emitting a value.

We could implement any of the two behaviors but I'm unsure about which alternative is the most useful. From the top of my head I think Bacons behavior makes more sense though.

What is your opinion @ccorcos?

**Comment by ccorcos** [comment]
Hmm. I think the primary use of takeUntil is control flow, but a lot of the time, its just used for cleanup. So in `a.takeUntil(b)`, I think it would make sense to end a when b ends OR emits a value.

I think the best thing to do is to give all kinds of options here and have some kind of consistent language. For example, maybe `on` means an event while `until` means event OR end. So you can have `a.stopOn(b)` to only stops on an event, but not when b ends.

**Comment by paldepind** [comment]
> Hmm. I think the primary use of takeUntil is control flow, but a lot of the time, its just used for cleanup. So in a.takeUntil(b), I think it would make sense to end a when b ends OR emits a value.

Ok. Then I will replicate the Rx behavior in `takeUntil`.

> I think the best thing to do is to give all kinds of options here and have some kind of consistent language. For example, maybe on means an event while until means event OR end. So you can have a.stopOn(b) to only stops on an event, but not when b ends.

That is a good idea!

**Comment by paldepind** [comment]
This has been implemented in [`flyd-takeuntil`](https://github.com/paldepind/flyd-takeuntil). Thanks to the new flexible stream ending behavior the implementation was very simple :)

**Comment by ccorcos** [comment]
Wow, thats nice a short :+1: 

So this part right here is just creating a clone of the src stream right?

```js
  flyd.stream([src], function(self) {
    self(src());
  })
```

It may be nice to have a function called `clone` or `fork` to do that. 

```js
flyd.endsOn(flyd.merge(term, src.end), flyd.fork(src))
```

Looks good!

**Comment by paldepind** [comment]
Yes. You could indeed call it a clone. I just realize that you could actually do it like this as well:

```javascript
flyd.map(function(v) { return v; }, src);
```

If this comes up a lot a `clone`/`fork` function would indeed be nice to have!
