### ISSUE TITLE
Sum example is outdated

### ISSUE THREAD

**Issue by ivan-kleshnin** [paldepind/flyd#93]
Since **0.2.0**

> Removed dependent stream syntax flyd.stream([streams], combinFn) in favor of the function combine. flyd.stream is now only used for creating top level streams.

But `sum` [example](https://github.com/paldepind/flyd/blob/master/examples/sum/index.html) still uses old syntax.

```js
import F from "flyd";

var x$ = F.stream(10);
var y$ = F.stream(20);
var sum$ = F.stream([x$, y$], function () {
  return x$() + y$();
});
```

As the very first example is broken people may encounter troubles getting into. 
I could make a PR to update sources but you need to update [hosted example](http://paldepind.github.io/flyd/examples/sum/) anyway.

**Comment by paldepind** [comment]
Yes. You are right. The sum example had been updated but the changes had not been merged into the GitHub page. The plain browser build needed updating as well.

Please reopen this issue if you find that something is still wrong.
